/*************************************************************************
 *** FORTE Library Element
 ***
 *** This file was generated using the 4DIAC FORTE Export Filter V1.0.x NG!
 ***
 *** Name: ACTION_CLIENT
 *** Description: Subapplication Type
 *** Version:
***     1.0: 2023-03-14/Tim Hesse -  - 
 *************************************************************************/

#include "ACTION_CLIENT.h"
#ifdef FORTE_ENABLE_GENERATED_SOURCE_CPP
#include "ACTION_CLIENT_gen.cpp"
#endif


DEFINE_FIRMWARE_FB(FORTE_ACTION_CLIENT, g_nStringIdACTION_CLIENT)

const CStringDictionary::TStringId FORTE_ACTION_CLIENT::scm_anDataInputNames[] = {g_nStringIdSEND_GOAL_REQ_QI, g_nStringIdSEND_GOAL_RES_QI, g_nStringIdCANCEL_GOAL_REQ_QI, g_nStringIdCANCEL_GOAL_RES_QI, g_nStringIdGET_RESULT_REQ_QI, g_nStringIdGET_RESULT_RES_QI, g_nStringIdFEEDBACK_QI, g_nStringIdTOPIC_NAME, g_nStringIdTOPIC_TYPE, g_nStringIdSEND_GOAL_REQ_DATA, g_nStringIdCANCEL_GOAL_REQ_DATA, g_nStringIdGET_RESULT_REQ_DATA};

const CStringDictionary::TStringId FORTE_ACTION_CLIENT::scm_anDataInputTypeIds[] = {g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdWSTRING, g_nStringIdWSTRING, g_nStringIdANY, g_nStringIdROS2_action_msgs__srv__CancelGoal__Request, g_nStringIdROS2_action_msgs__msg__GoalInfo};

const CStringDictionary::TStringId FORTE_ACTION_CLIENT::scm_anDataOutputNames[] = {g_nStringIdSEND_GOAL_REQ_QO, g_nStringIdSEND_GOAL_RES_QO, g_nStringIdCANCEL_GOAL_REQ_QO, g_nStringIdCANCEL_GOAL_RES_QO, g_nStringIdGET_RESULT_REQ_QO, g_nStringIdGET_RESULT_RES_QO, g_nStringIdFEEDBACK_QO, g_nStringIdSEND_GOAL_REQ_STATUS, g_nStringIdSEND_GOAL_RES_STATUS, g_nStringIdCANCEL_GOAL_REQ_STATUS, g_nStringIdCANCEL_GOAL_RES_STATUS, g_nStringIdGET_RESULT_REQ_STATUS, g_nStringIdGET_RESULT_RES_STATUS, g_nStringIdFEEDBACK_STATUS, g_nStringIdSEND_GOAL_RES_DATA, g_nStringIdCANCEL_GOAL_RES_DATA, g_nStringIdGET_RESULT_RES_DATA, g_nStringIdFEEDBACK_DATA};

const CStringDictionary::TStringId FORTE_ACTION_CLIENT::scm_anDataOutputTypeIds[] = {g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdBOOL, g_nStringIdWSTRING, g_nStringIdWSTRING, g_nStringIdWSTRING, g_nStringIdWSTRING, g_nStringIdWSTRING, g_nStringIdWSTRING, g_nStringIdWSTRING, g_nStringIdROS2_action_msgs__msg__GoalInfo, g_nStringIdROS2_action_msgs__srv__CancelGoal__Response, g_nStringIdANY, g_nStringIdANY};

const TForteInt16 FORTE_ACTION_CLIENT::scm_anEIWithIndexes[] = {-1, -1, -1, -1, -1, -1, -1, -1};
const CStringDictionary::TStringId FORTE_ACTION_CLIENT::scm_anEventInputNames[] = {g_nStringIdINIT, g_nStringIdSEND_GOAL_REQ, g_nStringIdSEND_GOAL_RSP, g_nStringIdCANCEL_GOAL_REQ, g_nStringIdCANCEL_GOAL_RSP, g_nStringIdGET_RESULT_REQ, g_nStringIdGET_RESULT_RSP, g_nStringIdFEEDBACK_RSP};

const TForteInt16 FORTE_ACTION_CLIENT::scm_anEOWithIndexes[] = {-1, -1, -1, -1, -1, -1, -1, -1};
const CStringDictionary::TStringId FORTE_ACTION_CLIENT::scm_anEventOutputNames[] = {g_nStringIdINITO, g_nStringIdSEND_GOAL_CNF, g_nStringIdSEND_GOAL_IND, g_nStringIdCANCEL_GOAL_CNF, g_nStringIdCANCEL_GOAL_IND, g_nStringIdGET_RESULT_CNF, g_nStringIdGET_RESULT_IND, g_nStringIdFEEDBACK_IND};


const SFBInterfaceSpec FORTE_ACTION_CLIENT::scm_stFBInterfaceSpec = {
  8, scm_anEventInputNames, nullptr, scm_anEIWithIndexes,
  8, scm_anEventOutputNames, nullptr, scm_anEOWithIndexes,
  12, scm_anDataInputNames, scm_anDataInputTypeIds,
  18, scm_anDataOutputNames, scm_anDataOutputTypeIds,
  0, nullptr
};

const SCFB_FBInstanceData FORTE_ACTION_CLIENT::scm_astInternalFBs[] = {
  {g_nStringIdSEND_GOAL, g_nStringIdDDS_PUB_SUB},
  {g_nStringIdSEND_GOAL_PUB_TYPE, g_nStringIdCONSTRUCT_DDS_TYPE},
  {g_nStringIdE_REND, g_nStringIdE_REND},
  {g_nStringIdE_REND_1, g_nStringIdE_REND},
  {g_nStringIdCANCEL_GOAL, g_nStringIdDDS_PUB_SUB},
  {g_nStringIdGET_RESULT, g_nStringIdDDS_PUB_SUB},
  {g_nStringIdE_REND_2, g_nStringIdE_REND},
  {g_nStringIdE_REND_3, g_nStringIdE_REND},
  {g_nStringIdCONSTRUCT_DDS_TYPE, g_nStringIdCONSTRUCT_DDS_TYPE},
  {g_nStringIdE_REND_4, g_nStringIdE_REND},
  {g_nStringIdFEEDBACK, g_nStringIdDDS_SUB},
  {g_nStringIdCONSTRUCT_DDS_TYPE_1, g_nStringIdCONSTRUCT_DDS_TYPE},
  {g_nStringIdE_REND_5, g_nStringIdE_REND},
  {g_nStringIdE_REND_6, g_nStringIdE_REND},
  {g_nStringIdE_REND_7, g_nStringIdE_REND},
  {g_nStringIdE_REND_8, g_nStringIdE_REND},
  {g_nStringIdSEND_GOAL_PUB_TOPIC, g_nStringIdCONSTRUCT_DDS_TOPIC},
  {g_nStringIdSEND_GOAL_SUB_TOPIC, g_nStringIdCONSTRUCT_DDS_TOPIC},
  {g_nStringIdGET_RESULT_PUB_TOPIC, g_nStringIdCONSTRUCT_DDS_TOPIC},
  {g_nStringIdGET_RESULT_SUB_TOPIC, g_nStringIdCONSTRUCT_DDS_TOPIC},
  {g_nStringIdCANCEL_GOAL_REQ_TOPIC, g_nStringIdCONSTRUCT_DDS_TOPIC},
  {g_nStringIdCANCEL_GOAL_RES_TOPIC, g_nStringIdCONSTRUCT_DDS_TOPIC},
  {g_nStringIdCONSTRUCT_FEEDBACK_TOPIC, g_nStringIdCONSTRUCT_DDS_TOPIC}
};

const SCFB_FBParameter FORTE_ACTION_CLIENT::scm_astParamters[] = {
  {0, g_nStringIdSUB_TYPE, "\"action_msgs::msg::dds_::GoalInfo_\""},
  {1, g_nStringIdSUFFIX, "\"_Goal_\""},
  {4, g_nStringIdPUB_TYPE, "\"action_msgs::srv::dds_::CancelGoal_Request_\""},
  {4, g_nStringIdSUB_TYPE, "\"action_msgs::srv::dds_::CancelGoal_Response_\""},
  {5, g_nStringIdPUB_TYPE, "\"action_msgs::msg::dds_::GoalInfo_\""},
  {8, g_nStringIdSUFFIX, "\"_Result_\""},
  {11, g_nStringIdSUFFIX, "\"_Feedback_\""},
  {16, g_nStringIdPREFIX, "\"rq\""},
  {16, g_nStringIdSUFFIX, "\"/_action/send_goalRequest\""},
  {17, g_nStringIdPREFIX, "\"rr\""},
  {17, g_nStringIdSUFFIX, "\"/_action/send_goalReply\""},
  {18, g_nStringIdPREFIX, "\"rq\""},
  {18, g_nStringIdSUFFIX, "\"/_action/get_resultRequest\""},
  {19, g_nStringIdPREFIX, "\"rr\""},
  {19, g_nStringIdSUFFIX, "\"/_action/get_resultReply\""},
  {20, g_nStringIdPREFIX, "\"rq\""},
  {20, g_nStringIdSUFFIX, "\"/_action/cancel_goalRequest\""},
  {21, g_nStringIdPREFIX, "\"rr\""},
  {21, g_nStringIdSUFFIX, "\"/_action/cancel_goalReply\""},
  {22, g_nStringIdPREFIX, "\"rt\""},
  {22, g_nStringIdSUFFIX, "\"/_action/feedback\""},
};

const SCFB_FBConnectionData FORTE_ACTION_CLIENT::scm_astEventConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND, g_nStringIdEO), 2, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_1, g_nStringIdEI1), 3},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_PUB_TYPE, g_nStringIdCNF), 1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_1, g_nStringIdEI2), 3},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_1, g_nStringIdEO), 3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdINIT), 0},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdINIT), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_PUB_TYPE, g_nStringIdREQ), 1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_2, g_nStringIdEO), 6, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdINIT), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_3, g_nStringIdEO), 7, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_4, g_nStringIdEI1), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_DDS_TYPE, g_nStringIdCNF), 8, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_4, g_nStringIdEI2), 9},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_4, g_nStringIdEO), 9, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdINIT), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_DDS_TYPE_1, g_nStringIdCNF), 11, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_5, g_nStringIdEI2), 12},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_5, g_nStringIdEO), 12, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdINIT), 10},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_REQ), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdREQ), 0},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_RSP), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdRSP), 0},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_REQ), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdREQ), 4},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_RSP), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdRSP), 4},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_REQ), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdREQ), 5},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_RSP), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdRSP), 5},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFEEDBACK_RSP), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdRSP), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdINITO), 0, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_6, g_nStringIdEI1), 13},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdINITO), 4, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_6, g_nStringIdEI2), 13},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_6, g_nStringIdEO), 13, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_7, g_nStringIdEI1), 14},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdINITO), 5, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_7, g_nStringIdEI2), 14},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdINITO), 10, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_8, g_nStringIdEI2), 15},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_7, g_nStringIdEO), 14, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_8, g_nStringIdEI1), 15},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_8, g_nStringIdEO), 15, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdINITO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdCNF), 0, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_CNF), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdIND), 0, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_IND), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdCNF), 4, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_CNF), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdIND), 4, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_IND), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdCNF), 5, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_CNF), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdIND), 5, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_IND), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdIND), 10, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFEEDBACK_IND), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_PUB_TOPIC, g_nStringIdCNF), 16, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND, g_nStringIdEI1), 2},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_SUB_TOPIC, g_nStringIdCNF), 17, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND, g_nStringIdEI2), 2},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT_PUB_TOPIC, g_nStringIdCNF), 18, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_3, g_nStringIdEI1), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT_SUB_TOPIC, g_nStringIdCNF), 19, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_3, g_nStringIdEI2), 7},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL_REQ_TOPIC, g_nStringIdCNF), 20, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_2, g_nStringIdEI1), 6},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL_RES_TOPIC, g_nStringIdCNF), 21, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_2, g_nStringIdEI2), 6},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_FEEDBACK_TOPIC, g_nStringIdCNF), 22, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdE_REND_5, g_nStringIdEI1), 12},
};

const SCFB_FBFannedOutConnectionData FORTE_ACTION_CLIENT::scm_astFannedOutEventConnections[] = {
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_DDS_TYPE, g_nStringIdREQ), 8},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_DDS_TYPE_1, g_nStringIdREQ), 11},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_PUB_TOPIC, g_nStringIdREQ), 16},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_SUB_TOPIC, g_nStringIdREQ), 17},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT_PUB_TOPIC, g_nStringIdREQ), 18},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT_SUB_TOPIC, g_nStringIdREQ), 19},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL_REQ_TOPIC, g_nStringIdREQ), 20},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL_RES_TOPIC, g_nStringIdREQ), 21},
  {3, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_FEEDBACK_TOPIC, g_nStringIdREQ), 22},
};

const SCFB_FBConnectionData FORTE_ACTION_CLIENT::scm_astDataConnections[] = {
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_PUB_TYPE, g_nStringIdDDS_TYPE), 1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdPUB_TYPE), 0},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTOPIC_TYPE), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_PUB_TYPE, g_nStringIdROS2_TYPE), 1},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_REQ_DATA), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdPUB_DATA), 0},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_REQ_DATA), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdPUB_DATA), 4},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_REQ_QI), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdPUB_QI), 0},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_RES_QI), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdSUB_QI), 0},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_REQ_QI), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdPUB_QI), 4},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_RES_QI), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdSUB_QI), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_DDS_TYPE, g_nStringIdDDS_TYPE), 8, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdSUB_TYPE), 5},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_REQ_DATA), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdPUB_DATA), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_DDS_TYPE_1, g_nStringIdDDS_TYPE), 11, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdTYPE), 10},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_REQ_QI), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdPUB_QI), 5},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_RES_QI), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdSUB_QI), 5},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFEEDBACK_QI), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdQI), 10},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdPUB_QO), 0, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_REQ_QO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdSUB_QO), 0, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_RES_QO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdPUB_QO), 4, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_REQ_QO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdSUB_QO), 4, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_RES_QO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdPUB_QO), 5, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_REQ_QO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdSUB_QO), 5, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_RES_QO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdQO), 10, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFEEDBACK_QO), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdPUB_STATUS), 0, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_REQ_STATUS), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdSUB_STATUS), 0, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_RES_STATUS), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdPUB_STATUS), 4, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_REQ_STATUS), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdSUB_STATUS), 4, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_RES_STATUS), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdPUB_STATUS), 5, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_REQ_STATUS), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdSUB_STATUS), 5, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_RES_STATUS), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdSTATUS), 10, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFEEDBACK_STATUS), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdSUB_DATA), 10, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdFEEDBACK_DATA), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdSUB_DATA), 5, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdGET_RESULT_RES_DATA), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdSUB_DATA), 4, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdCANCEL_GOAL_RES_DATA), -1},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdSUB_DATA), 0, GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdSEND_GOAL_RES_DATA), -1},
  {GENERATE_CONNECTION_PORT_ID_1_ARG(g_nStringIdTOPIC_NAME), -1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_PUB_TOPIC, g_nStringIdROS2_TOPIC), 16},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_PUB_TOPIC, g_nStringIdDDS_TOPIC), 16, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdPUB_TOPIC), 0},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_SUB_TOPIC, g_nStringIdDDS_TOPIC), 17, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL, g_nStringIdSUB_TOPIC), 0},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT_PUB_TOPIC, g_nStringIdDDS_TOPIC), 18, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdPUB_TOPIC), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT_SUB_TOPIC, g_nStringIdDDS_TOPIC), 19, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT, g_nStringIdSUB_TOPIC), 5},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL_REQ_TOPIC, g_nStringIdDDS_TOPIC), 20, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdPUB_TOPIC), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL_RES_TOPIC, g_nStringIdDDS_TOPIC), 21, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL, g_nStringIdSUB_TOPIC), 4},
  {GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_FEEDBACK_TOPIC, g_nStringIdDDS_TOPIC), 22, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdFEEDBACK, g_nStringIdTOPIC), 10},
};

const SCFB_FBFannedOutConnectionData FORTE_ACTION_CLIENT::scm_astFannedOutDataConnections[] = {
  {1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_DDS_TYPE, g_nStringIdROS2_TYPE), 8},
  {1, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_DDS_TYPE_1, g_nStringIdROS2_TYPE), 11},
  {32, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdSEND_GOAL_SUB_TOPIC, g_nStringIdROS2_TOPIC), 17},
  {32, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT_PUB_TOPIC, g_nStringIdROS2_TOPIC), 18},
  {32, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdGET_RESULT_SUB_TOPIC, g_nStringIdROS2_TOPIC), 19},
  {32, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL_REQ_TOPIC, g_nStringIdROS2_TOPIC), 20},
  {32, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCANCEL_GOAL_RES_TOPIC, g_nStringIdROS2_TOPIC), 21},
  {32, GENERATE_CONNECTION_PORT_ID_2_ARG(g_nStringIdCONSTRUCT_FEEDBACK_TOPIC, g_nStringIdROS2_TOPIC), 22},
};

const SCFB_FBNData FORTE_ACTION_CLIENT::scm_stFBNData = {
  23, scm_astInternalFBs,
  38, scm_astEventConnections,
  9, scm_astFannedOutEventConnections,
  40, scm_astDataConnections,
  8, scm_astFannedOutDataConnections,
  21, scm_astParamters
};



